<?php

if ((int)$this->getCurrentCategory()->getIsAnchor() && 
    !Mage::getStoreConfig('easy_catalogimg/general/anchor')) {
    
    return;        
}

$columnsCount = (int)Mage::getStoreConfig('easy_catalogimg/general/columnsCount');
$_categories = $this->getCurrentChildCategories();

if (is_array($_categories)) {
    $_collectionSize = count($_categories);
} else {
    $_collectionSize = $_categories->count();
} 
?>
<?php if ($_collectionSize): ?> 
<div class="browse-categories-inner"><img src="<?php echo $this->getskinUrl("images/frontpage-browsecategories.jpg");?>" border="0"></div>
<div class="listing-catalogimg-grid catalogimg-listing">   
    <?php $i=0; foreach ($_categories as $_category): 
        if (!$_category->getIsActive()): continue; endif;
            $cur_category=Mage::getModel('catalog/category')->load($_category->getId());
            $imageUrl = $cur_category->getImageUrl();
        if (empty($imageUrl)): $imageUrl = $this->getSkinUrl('img/holder_170.jpg'); endif;
    ?>
    
    <?php if($i++%$columnsCount==0): ?>
        <ol class="grid-row">
    <?php endif; ?>
        <?php if ($i%($columnsCount) == 0)
                // Edge of the row
                echo '<li class="item last" style="border-right :1px solid #d7d7d7; width: 136px;">'; 
            else if ($i%($columnsCount) != 0 && $i != $_collectionSize)
                echo '<li class="item">'; 
            else 
                echo '<li class="item" style="border-right :1px solid #d7d7d7;">';  
        ?>
            <div class="category-entry">
                <a href="<?php echo $_category->getUrl() ?>" title="<?php echo $this->htmlEscape($_category->getName())?>" class="product-image">
                <img src="<?php echo $imageUrl ?>" width="95" alt="<?php echo $this->htmlEscape($_category->getName()) ?>"/></a>
                <h3><a class="smalllinkh3" href="<?php echo $_category->getUrl() ?>" title="<?php echo $this->htmlEscape($_category->getName()) ?>"><?php echo $this->htmlEscape($_category->getName()) ?></a></h3>
                <?php /*?><a href="<?php echo $_category->getUrl() ?>">
                <img class="shop-now" src="<?php echo $this->getSkinUrl('img/shopnow-button.gif'); ?>" /></a><?php */?>
            </div>
        </li>   
    <?php if($i%$columnsCount==0 || $i==$_collectionSize): ?>
        </ol>
    <?php endif; ?>
    
    <?php endforeach; ?> 
    <script type="text/javascript">decorateGeneric($$('.grid-row'), ['last', 'odd', 'even']);</script>
</div>
<?php endif; ?>