<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>
<?php
    $_helper    = $this->helper('catalog/output');
    $_category = $this->getCurrentCategory();
    $_imgHtml   = '';
    
    if ($_imageUrl = $_category->getImageUrl()) {
        $_imgHtml = '<img src="'.$_imageUrl.'" alt="'.$this->htmlEscape($_category->getName()).'" width="475" />';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php if($this->isContentMode()): /* Sub Category pages - no products CONTENT MODE*/ ?>

    <div class="category-title">
    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-feed right"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
    <h1><?php echo $_helper->categoryAttribute($_category, $this->htmlEscape($_category->getName()), 'name') ?></h1>
    </div>
    <?php if($_imgHtml): ?>
        <p><?php // echo $_imgHtml?></p>
    <?php endif; ?>
    <?php if($_description=$_category->getDescription()): ?>
        <p class="category-description"><?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?></p>
    <?php endif; ?>
	
	<!--Add By Kin-->
		<?php  if((isset($_REQUEST['page'])) && (strtoupper($_helper->categoryAttribute($_category, $this->htmlEscape($_category->getName()), 'name')) != 'INK & TONER')) {			
			//echo $this->getLayout()->createBlock('cms/block')->setBlockId('ink_toner_block')->toHtml() ;
		 }
		?>
	<!--Complete By Kin-->
    <?php echo $this->getCmsBlockHtml() ?>
    
<?php elseif($this->isMixedMode()): /*Category Listing Page - with products (mixed mode?) */ ?>

    <div class="category-title">
    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-feed right"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
    <h1><?php echo $_helper->categoryAttribute($_category, $this->htmlEscape($_category->getName()), 'name') ?></h1>
    </div>
    <?php if($_imgHtml): ?>
        <p><?php // echo $_imgHtml?></p>
    <?php endif; ?>
    <?php /*
    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-feed"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?> */ ?>
	
	
	
	<!--Add By Kin-->
	<?php  if(isset($_REQUEST['page'])) {	
	//echo $this->getLayout()->createBlock('cms/block')->setBlockId('ink_toner_block')->toHtml() ;
	}
	?>
	
	<?php echo $this->getCmsBlockHtml() ?>
	
	<?php  if(isset($_REQUEST['page'])) {	
	 if(isset($_REQUEST['search'])) { 	?>
			<?php echo $this->getChildHtml('subcategories') ?>
			<?php $categories = $this->getCurrentCategory()->getChildrenCategories();
				$countCategories = is_array($categories) ? count($categories) : $categories->getSize();
			?>
			<?php // if (Mage::getStoreConfig('easy_catalogimg/general/plisting') || ($countCategories == 0)) : ?>
			<?php if (($countCategories == 0)) : ?>
				<?php echo $this->getProductListHtml() ?>
			<?php endif;?>
			<br />
			<?php if($_description=$_category->getDescription()): ?>
				<p class="category-description"><?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?></p>
			<?php endif; ?>
			<?php	} 	
		}
		else
		{
			?>
			<?php echo $this->getChildHtml('subcategories') ?>
			<?php $categories = $this->getCurrentCategory()->getChildrenCategories();
				$countCategories = is_array($categories) ? count($categories) : $categories->getSize();
			?>
			<?php // if (Mage::getStoreConfig('easy_catalogimg/general/plisting') || ($countCategories == 0)) : ?>
			<?php if (($countCategories == 0)) : ?>
				<?php echo $this->getProductListHtml() ?>
			<?php endif;?>
			<br />
			<?php if($_description=$_category->getDescription()): ?>
				<p class="category-description"><?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?></p>
			<?php endif; ?>
			<?php
		}
		?>
	<!--Complete By Kin-->
	
    <?php // echo $this->getCmsBlockHtml() ?>
    
    
<?php else: /*Category Listing Page - with products */ ?>

    <div class="category-title">
    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-feed right"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
	<?php
	//print_r($_category);
	//echo "<br/>1==".$this->htmlEscape($_category->getName());
	//echo "<br/>2==".$_helper->categoryAttribute($_category, $this->htmlEscape($_category->getName()), 'name');
	?>
    <h1><?php // echo $_helper->categoryAttribute($_category, $this->htmlEscape($_category->getName()), 'name') 
	echo $this->htmlEscape($_category->getName()); ?>
	</h1>
    </div>
    <?php if($_imgHtml): ?>
        <p><?php // echo $_imgHtml?></p>
    <?php endif; ?>


	<!--Add By Kin-->
	<?php  if(isset($_REQUEST['page'])) {	
		//echo "<br/>";
		//echo $this->getLayout()->createBlock('cms/block')->setBlockId('ink_toner_block')->toHtml() ;
		 if(isset($_REQUEST['search'])) { 	?>
			 
		 <?php echo $this->getChildHtml('subcategories') ?>
		<?php $categories = $this->getCurrentCategory()->getChildrenCategories();
			$countCategories = is_array($categories) ? count($categories) : $categories->getSize();
		?>
		<?php // printf("countCategories: ".$countCategories); ?>
		<?php // if (Mage::getStoreConfig('easy_catalogimg/general/plisting') || ($countCategories == 0)) : ?>  
		<?php if (($countCategories == 0)) : ?>            
		<?php  echo $this->getProductListHtml() ?> 
	
		<?php endif;?>
		<br />
		<?php if($_description=$_category->getDescription()): ?>
			<p class="category-description"><?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?></p>
		<?php endif; ?> 
		
		 <?php } ?>
	
	<?php
	}
	else
	{
		?>
		<?php echo $this->getChildHtml('subcategories') ?>
		<?php $categories = $this->getCurrentCategory()->getChildrenCategories();
			$countCategories = is_array($categories) ? count($categories) : $categories->getSize();
		?>
		<?php // printf("countCategories: ".$countCategories); ?>
		<?php // if (Mage::getStoreConfig('easy_catalogimg/general/plisting') || ($countCategories == 0)) : ?>  
		<?php if (($countCategories == 0)) : ?>            
		<?php  echo $this->getProductListHtml() ?> 
	
		<?php endif;?>
		<br />
		<?php if($_description=$_category->getDescription()): ?>
			<p class="category-description"><?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?></p>
		<?php endif; ?>  
		<?php
	}
	?>
	<!--Complete By Kin-->
	   

<?php endif; ?>